<?php

namespace Database\Seeders;

use App\Models\Ledger;
use Illuminate\Database\Seeder;

class VendorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Ledger::insert([
            ['ledger_name'=>'Kalikrishna Kangsa Banik','billing_name'=>'Kalikrishna Kangsa Banik','ledger_group_id'=>'15','address1'=>'Duttapukur','mobile1'=>'9830948897','mobile2'=>'','state_id'=>20,'pin'=>'743248','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Manoj Raj Bangshi','billing_name'=>'Manoj Raj Bangshi','ledger_group_id'=>'15','address1'=>'Nabadwip','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Cash Purchase','billing_name'=>'Cash Purchase','ledger_group_id'=>'15','address1'=>'Kolkata','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Sakil','billing_name'=>'Sakil','ledger_group_id'=>'15','address1'=>'Jaipur','mobile1'=>'999999999','mobile2'=>'','state_id'=>20,'pin'=>'2','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Azim ','billing_name'=>'Azim ','ledger_group_id'=>'15','address1'=>'Moradabad','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Rabi Banerjee','billing_name'=>'Rabi Banerjee','ledger_group_id'=>'15','address1'=>'Habra','mobile1'=>'9007863215','mobile2'=>'','state_id'=>20,'pin'=>'743271','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Pradeep Das','billing_name'=>'Pradeep Das','ledger_group_id'=>'15','address1'=>'Patrasayer','mobile1'=>'9745612322','mobile2'=>'','state_id'=>20,'pin'=>'1','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Som ','billing_name'=>'Som ','ledger_group_id'=>'15','address1'=>'Banipur, Habra','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'P P Gupta','billing_name'=>'P P Gupta','ledger_group_id'=>'15','address1'=>'Jalesar','mobile1'=>'7351552288','mobile2'=>'','state_id'=>20,'pin'=>'244001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Haripada Kangsa Banik','billing_name'=>'Haripada Kangsa Banik','ledger_group_id'=>'15','address1'=>'Bally','mobile1'=>'9434125635','mobile2'=>'','state_id'=>20,'pin'=>'711201','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'J K Banik','billing_name'=>'J K Banik','ledger_group_id'=>'15','address1'=>'Duttapukur','mobile1'=>'99999999991','mobile2'=>'','state_id'=>20,'pin'=>'743271','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Sanjay Biswas','billing_name'=>'Sanjay Biswas','ledger_group_id'=>'15','address1'=>'Gobardanga','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Manik China','billing_name'=>'Manik China','ledger_group_id'=>'15','address1'=>'Kolkata','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Jadab Kangsa Banik ','billing_name'=>'Jadab Kangsa Banik ','ledger_group_id'=>'15','address1'=>'Duttapukur','mobile1'=>'9434125489','mobile2'=>'','state_id'=>20,'pin'=>'743248','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Anjali','billing_name'=>'Anjali','ledger_group_id'=>'15','address1'=>'Bally','mobile1'=>'9999999992','mobile2'=>'','state_id'=>20,'pin'=>'7','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Lokenath Metal (Gautam)','billing_name'=>'Lokenath Metal (Gautam)','ledger_group_id'=>'15','address1'=>'Bally','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Aaryan Co.','billing_name'=>'Aaryan Co.','ledger_group_id'=>'15','address1'=>'Hindmotor','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Indrajit Acharjee','billing_name'=>'Indrajit Acharjee','ledger_group_id'=>'15','address1'=>'Habra','mobile1'=>'9564779896','mobile2'=>'','state_id'=>20,'pin'=>'743263','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Tapan Kaku','billing_name'=>'Tapan Kaku','ledger_group_id'=>'15','address1'=>'Bally','mobile1'=>'9999999993','mobile2'=>'','state_id'=>20,'pin'=>'7','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Kansabanik Enterprise (Gobindo)','billing_name'=>'Kansabanik Enterprise (Gobindo)','ledger_group_id'=>'15','address1'=>'Duttapukur','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Ramesh','billing_name'=>'Ramesh','ledger_group_id'=>'15','address1'=>'Hindmotor','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Bhasan Kansabanik','billing_name'=>'Bhasan Kansabanik','ledger_group_id'=>'15','address1'=>'Bally','mobile1'=>'9999999994','mobile2'=>'','state_id'=>20,'pin'=>'7','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'A R Ghoongroo','billing_name'=>'A R Ghoongroo','ledger_group_id'=>'15','address1'=>'Kolkata','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Biswanath Kangsa Banik','billing_name'=>'Biswanath Kangsa Banik','ledger_group_id'=>'15','address1'=>'Banipur','mobile1'=>'9456123911','mobile2'=>'','state_id'=>20,'pin'=>'743233','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Brojo Gopal Gyin','billing_name'=>'Brojo Gopal Gyin','ledger_group_id'=>'15','address1'=>'Duttapukur','mobile1'=>'9999999995','mobile2'=>'','state_id'=>20,'pin'=>'7','transaction_type_id'=>2,'opening_balance'=>25145],
            ['ledger_name'=>'La Coppera ','billing_name'=>'La Coppera ','ledger_group_id'=>'15','address1'=>'Mathura','mobile1'=>'09837061366','mobile2'=>'','state_id'=>20,'pin'=>'281004','transaction_type_id'=>2,'opening_balance'=>440182],
            ['ledger_name'=>'Jugal Kangsa Banik','billing_name'=>'Jugal Kangsa Banik','ledger_group_id'=>'15','address1'=>'Duttapukur','mobile1'=>'9956199299','mobile2'=>'','state_id'=>20,'pin'=>'743238','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Sadhan Ghosh','billing_name'=>'Sadhan Ghosh','ledger_group_id'=>'15','address1'=>'Matiyari','mobile1'=>'9999999997','mobile2'=>'','state_id'=>20,'pin'=>'7','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Tarapada Silpalay','billing_name'=>'Tarapada Silpalay','ledger_group_id'=>'15','address1'=>'Sheoraphuli','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>16335],
            ['ledger_name'=>'Shree Shee Metal','billing_name'=>'Shree Shee Metal','ledger_group_id'=>'15','address1'=>'Moradabad','mobile1'=>'9','mobile2'=>'','state_id'=>20,'pin'=>'4','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Udps','billing_name'=>'Udps','ledger_group_id'=>'15','address1'=>'Duttapukur','mobile1'=>'9965652533','mobile2'=>'','state_id'=>20,'pin'=>'743238','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Bapi ','billing_name'=>'Bapi ','ledger_group_id'=>'15','address1'=>'Nabadwip','mobile1'=>'9','mobile2'=>'','state_id'=>20,'pin'=>'7','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Rahemat Ali','billing_name'=>'Rahemat Ali','ledger_group_id'=>'15','address1'=>'Kolkata','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Nakul Ch. Rana','billing_name'=>'Nakul Ch. Rana','ledger_group_id'=>'15','address1'=>'Mahishadal','mobile1'=>'9878456922','mobile2'=>'','state_id'=>20,'pin'=>'721628','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'New Basanti','billing_name'=>'New Basanti','ledger_group_id'=>'15','address1'=>'Burra Bazar','mobile1'=>'9','mobile2'=>'','state_id'=>20,'pin'=>'7','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Paras Metal','billing_name'=>'Paras Metal','ledger_group_id'=>'15','address1'=>'Kolkata','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Sadananda','billing_name'=>'Sadananda','ledger_group_id'=>'15','address1'=>'Bally','mobile1'=>'8956247987','mobile2'=>'','state_id'=>20,'pin'=>'711201','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Manik Kangsa Banik','billing_name'=>'Manik Kangsa Banik','ledger_group_id'=>'15','address1'=>'Bally','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Sudangshu Banik','billing_name'=>'Sudangshu Banik','ledger_group_id'=>'15','address1'=>'Bally','mobile1'=>'9654896999','mobile2'=>'','state_id'=>20,'pin'=>'711201','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Uttam (Habra)','billing_name'=>'Uttam (Habra)','ledger_group_id'=>'15','address1'=>'Habra','mobile1'=>'9','mobile2'=>'','state_id'=>20,'pin'=>'743271','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Sujit','billing_name'=>'Sujit','ledger_group_id'=>'15','address1'=>'Duttapukur','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Mashkoor','billing_name'=>'Mashkoor','ledger_group_id'=>'15','address1'=>'Moradabad','mobile1'=>'8171449860','mobile2'=>'','state_id'=>20,'pin'=>'4','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Kedar Babu','billing_name'=>'Kedar Babu','ledger_group_id'=>'15','address1'=>'Bankura','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Anil Ch. Das','billing_name'=>'Anil Ch. Das','ledger_group_id'=>'15','address1'=>'Sheoraphuli','mobile1'=>'8956784222','mobile2'=>'','state_id'=>20,'pin'=>'712223','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Kalikrishna Pramanick','billing_name'=>'Kalikrishna Pramanick','ledger_group_id'=>'15','address1'=>'Bashberia','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'7','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Deepak Kangsa Banik (J.K)','billing_name'=>'Deepak Kangsa Banik (J.K)','ledger_group_id'=>'15','address1'=>'Duttapukur','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Gautam','billing_name'=>'Gautam','ledger_group_id'=>'15','address1'=>'Simla Street','mobile1'=>'9898982536','mobile2'=>'','state_id'=>20,'pin'=>'7000006','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Kasinath Das (Kd)','billing_name'=>'Kasinath Das (Kd)','ledger_group_id'=>'15','address1'=>'Matiyari','mobile1'=>'9','mobile2'=>'','state_id'=>20,'pin'=>'7','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Mohan Ch. Karmakar','billing_name'=>'Mohan Ch. Karmakar','ledger_group_id'=>'15','address1'=>'Patrasayer','mobile1'=>'9669878722','mobile2'=>'','state_id'=>20,'pin'=>'722206','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Jamil','billing_name'=>'Jamil','ledger_group_id'=>'15','address1'=>'A','mobile1'=>'9','mobile2'=>'','state_id'=>20,'pin'=>'7','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Shri Balaji Metal','billing_name'=>'Shri Balaji Metal','ledger_group_id'=>'15','address1'=>'Jalesar','mobile1'=>'9457104090','mobile2'=>'','state_id'=>20,'pin'=>'207302','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Samsuiddin','billing_name'=>'Samsuiddin','ledger_group_id'=>'15','address1'=>'Moradabad','mobile1'=>'09557968786','mobile2'=>'','state_id'=>20,'pin'=>'244001','transaction_type_id'=>2,'opening_balance'=>144670],
            ['ledger_name'=>'Noor Jahan','billing_name'=>'Noor Jahan','ledger_group_id'=>'15','address1'=>'Labpur','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Classic','billing_name'=>'Classic','ledger_group_id'=>'15','address1'=>'Moradabad','mobile1'=>'09411857996','mobile2'=>'','state_id'=>20,'pin'=>'244001','transaction_type_id'=>2,'opening_balance'=>320457],
            ['ledger_name'=>'Suresh Singh','billing_name'=>'Suresh Singh','ledger_group_id'=>'15','address1'=>'Simley','mobile1'=>'9','mobile2'=>'','state_id'=>20,'pin'=>'7','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Pratik Metal','billing_name'=>'Pratik Metal','ledger_group_id'=>'15','address1'=>'Kolkata','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Chacha','billing_name'=>'Chacha','ledger_group_id'=>'15','address1'=>'Moradabad','mobile1'=>'07983667524','mobile2'=>'','state_id'=>20,'pin'=>'244001','transaction_type_id'=>2,'opening_balance'=>353614],
            ['ledger_name'=>'Ankur','billing_name'=>'Ankur','ledger_group_id'=>'15','address1'=>'Mathura','mobile1'=>'9412279332','mobile2'=>'','state_id'=>20,'pin'=>'281001','transaction_type_id'=>2,'opening_balance'=>103550],
            ['ledger_name'=>'Debasish Ghosh','billing_name'=>'Debasish Ghosh','ledger_group_id'=>'15','address1'=>'Matiyari','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'R. K. D.','billing_name'=>'R. K. D.','ledger_group_id'=>'15','address1'=>'Moradabad','mobile1'=>'07060098452','mobile2'=>'','state_id'=>20,'pin'=>'244001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Jogobondhu K Banik','billing_name'=>'Jogobondhu K Banik','ledger_group_id'=>'15','address1'=>'Muchibajar','mobile1'=>'9','mobile2'=>'','state_id'=>20,'pin'=>'7','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Himalaya','billing_name'=>'Himalaya','ledger_group_id'=>'15','address1'=>'Rewari','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Arshad','billing_name'=>'Arshad','ledger_group_id'=>'15','address1'=>'Moradabad','mobile1'=>'07906840418','mobile2'=>'','state_id'=>20,'pin'=>'244001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Tarak Da','billing_name'=>'Tarak Da','ledger_group_id'=>'15','address1'=>'Burra Bazar','mobile1'=>'9','mobile2'=>'','state_id'=>20,'pin'=>'7','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Faizan','billing_name'=>'Faizan','ledger_group_id'=>'15','address1'=>'Moradabad','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Maharaja','billing_name'=>'Maharaja','ledger_group_id'=>'15','address1'=>'Moradabad','mobile1'=>'09411097728','mobile2'=>'','state_id'=>20,'pin'=>'244001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Monoranjan Kangsa Banik','billing_name'=>'Monoranjan Kangsa Banik','ledger_group_id'=>'15','address1'=>'L','mobile1'=>'9','mobile2'=>'','state_id'=>20,'pin'=>'7','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Mintu Sarkar','billing_name'=>'Mintu Sarkar','ledger_group_id'=>'15','address1'=>'Chakdah','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Monu ','billing_name'=>'Monu ','ledger_group_id'=>'15','address1'=>'Rewari ','mobile1'=>'09416890110','mobile2'=>'','state_id'=>20,'pin'=>'123401','transaction_type_id'=>2,'opening_balance'=>781972],
            ['ledger_name'=>'X','billing_name'=>'X','ledger_group_id'=>'15','address1'=>'R','mobile1'=>'9','mobile2'=>'','state_id'=>20,'pin'=>'7','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Mahesh Prasad Batuk Prasad','billing_name'=>'Mahesh Prasad Batuk Prasad','ledger_group_id'=>'15','address1'=>'Ck. 49/44A, Bhuletan, Varanasi 221001','mobile1'=>'9936897508','mobile2'=>'','state_id'=>20,'pin'=>'221001','transaction_type_id'=>2,'opening_balance'=>157567],
            ['ledger_name'=>'D.C.D','billing_name'=>'D.C.D','ledger_group_id'=>'15','address1'=>'Matiyari','mobile1'=>'9998887772','mobile2'=>'','state_id'=>20,'pin'=>'743263','transaction_type_id'=>2,'opening_balance'=>120000],
            ['ledger_name'=>'G K Basu','billing_name'=>'G K Basu','ledger_group_id'=>'15','address1'=>'Burrabazar','mobile1'=>'9','mobile2'=>'','state_id'=>20,'pin'=>'7','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Rakesh Babu','billing_name'=>'Rakesh Babu','ledger_group_id'=>'15','address1'=>'Jaleswar','mobile1'=>'9','mobile2'=>'','state_id'=>20,'pin'=>'4','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Gokul Kangsa Banik','billing_name'=>'Gokul Kangsa Banik','ledger_group_id'=>'15','address1'=>'Kannagar','mobile1'=>'9','mobile2'=>'','state_id'=>20,'pin'=>'7','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Modhu Kangsa Banik (Tapa)','billing_name'=>'Modhu Kangsa Banik (Tapa)','ledger_group_id'=>'15','address1'=>'Nabadwip','mobile1'=>'9','mobile2'=>'','state_id'=>20,'pin'=>'7','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Tapas','billing_name'=>'Tapas','ledger_group_id'=>'15','address1'=>'Bally','mobile1'=>'9','mobile2'=>'','state_id'=>20,'pin'=>'7','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Ram Hari Kangsa Banik','billing_name'=>'Ram Hari Kangsa Banik','ledger_group_id'=>'15','address1'=>'Bally','mobile1'=>'9','mobile2'=>'','state_id'=>20,'pin'=>'7','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Budu Ghosh','billing_name'=>'Budu Ghosh','ledger_group_id'=>'15','address1'=>'Matiyari','mobile1'=>'9','mobile2'=>'','state_id'=>20,'pin'=>'7','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Sudipto Dutta','billing_name'=>'Sudipto Dutta','ledger_group_id'=>'15','address1'=>'Matiyari','mobile1'=>'9','mobile2'=>'','state_id'=>20,'pin'=>'7','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Ami','billing_name'=>'Ami','ledger_group_id'=>'15','address1'=>'L','mobile1'=>'9','mobile2'=>'','state_id'=>20,'pin'=>'7','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Bhaeromal Varanasi','billing_name'=>'Bhaeromal Varanasi','ledger_group_id'=>'15','address1'=>'Benaras','mobile1'=>'9','mobile2'=>'','state_id'=>20,'pin'=>'7','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Sanjay Kangsa Banik','billing_name'=>'Sanjay Kangsa Banik','ledger_group_id'=>'15','address1'=>'Bally','mobile1'=>'9','mobile2'=>'','state_id'=>20,'pin'=>'7','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Pankaj Agarwal','billing_name'=>'Pankaj Agarwal','ledger_group_id'=>'15','address1'=>'Hathras','mobile1'=>'8449440006','mobile2'=>'','state_id'=>20,'pin'=>'2','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Sibu Kangsa Banik','billing_name'=>'Sibu Kangsa Banik','ledger_group_id'=>'15','address1'=>'L','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'7','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Munna','billing_name'=>'Munna','ledger_group_id'=>'15','address1'=>'Kolkata','mobile1'=>'9','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Monoronjon','billing_name'=>'Monoronjon','ledger_group_id'=>'15','address1'=>'Muchibajar','mobile1'=>'9','mobile2'=>'','state_id'=>20,'pin'=>'7','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Toton','billing_name'=>'Toton','ledger_group_id'=>'15','address1'=>'Bally','mobile1'=>'9','mobile2'=>'','state_id'=>20,'pin'=>'7','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Kamal Kangsa Banik','billing_name'=>'Kamal Kangsa Banik','ledger_group_id'=>'15','address1'=>'Kolkata','mobile1'=>'9','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Montu','billing_name'=>'Montu','ledger_group_id'=>'15','address1'=>'Kolkata','mobile1'=>'7','mobile2'=>'','state_id'=>20,'pin'=>'7','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Jamir','billing_name'=>'Jamir','ledger_group_id'=>'15','address1'=>'Kolkata','mobile1'=>'9','mobile2'=>'','state_id'=>20,'pin'=>'7','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Parvez Khan','billing_name'=>'Parvez Khan','ledger_group_id'=>'15','address1'=>'Moradabad','mobile1'=>'9997083575','mobile2'=>'','state_id'=>20,'pin'=>'4','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Ajit Sarnakar','billing_name'=>'Ajit Sarnakar','ledger_group_id'=>'15','address1'=>'Kolkata','mobile1'=>'9143258372','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Sattvic Cosmocare','billing_name'=>'Sattvic Cosmocare','ledger_group_id'=>'15','address1'=>'71, Bartala Street, 2Nd Floor','mobile1'=>'7439037676','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Sumon Mondol','billing_name'=>'Sumon Mondol','ledger_group_id'=>'15','address1'=>'Kolkata','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Nirmal Kangsa Banik (Ashirbad)','billing_name'=>'Nirmal Kangsa Banik (Ashirbad)','ledger_group_id'=>'15','address1'=>'Bally','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'743112','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Moti','billing_name'=>'Moti','ledger_group_id'=>'15','address1'=>'Kolkata','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Mohon Karmakar','billing_name'=>'Mohon Karmakar','ledger_group_id'=>'15','address1'=>'Patrasayer','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Sanjit Kundu','billing_name'=>'Sanjit Kundu','ledger_group_id'=>'15','address1'=>'Nabadip','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Impex','billing_name'=>'Impex','ledger_group_id'=>'15','address1'=>'Moradabad','mobile1'=>'9411969982','mobile2'=>'','state_id'=>20,'pin'=>'444001','transaction_type_id'=>2,'opening_balance'=>110000],
            ['ledger_name'=>'Dutta Brothers','billing_name'=>'Dutta Brothers','ledger_group_id'=>'15','address1'=>'Matiyari','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Tarak Saha ','billing_name'=>'Tarak Saha ','ledger_group_id'=>'15','address1'=>'Nabadwip','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Arohi Traders','billing_name'=>'Arohi Traders','ledger_group_id'=>'15','address1'=>'Kolkata','mobile1'=>'9831110286','mobile2'=>'','state_id'=>20,'pin'=>'711101','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Manohar','billing_name'=>'Manohar','ledger_group_id'=>'15','address1'=>'Patna','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Brojen Das','billing_name'=>'Brojen Das','ledger_group_id'=>'15','address1'=>'Sheraphuli','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Bdk','billing_name'=>'Bdk','ledger_group_id'=>'15','address1'=>'Bankura','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Adi Sree Durga','billing_name'=>'Adi Sree Durga','ledger_group_id'=>'15','address1'=>'Kolkata','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Sutapan Ghosh','billing_name'=>'Sutapan Ghosh','ledger_group_id'=>'15','address1'=>'Nabadwip','mobile1'=>'9932397409','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Sanatan (Mp)','billing_name'=>'Sanatan (Mp)','ledger_group_id'=>'15','address1'=>'Baranagar','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Sanjay Raha','billing_name'=>'Sanjay Raha','ledger_group_id'=>'15','address1'=>'Kolkata','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Navjyoti Enterprise','billing_name'=>'Navjyoti Enterprise','ledger_group_id'=>'15','address1'=>'Manohar Colony Jagadhari','mobile1'=>'9896045947','mobile2'=>'','state_id'=>20,'pin'=>'135001','transaction_type_id'=>2,'opening_balance'=>609632],
            ['ledger_name'=>'Rabi Dhar','billing_name'=>'Rabi Dhar','ledger_group_id'=>'15','address1'=>'Berhampore','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Lokenath','billing_name'=>'Lokenath','ledger_group_id'=>'15','address1'=>'Duttapukur','mobile1'=>'9874114986','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Raees','billing_name'=>'Raees','ledger_group_id'=>'15','address1'=>'Kolkata','mobile1'=>'9932077248','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Bihari Gobndo Kundu','billing_name'=>'Bihari Gobndo Kundu','ledger_group_id'=>'15','address1'=>'Kolkata','mobile1'=>'7','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0],
            ['ledger_name'=>'Baiya','billing_name'=>'Baiya','ledger_group_id'=>'15','address1'=>'Odisha','mobile1'=>'8','mobile2'=>'','state_id'=>20,'pin'=>'700001','transaction_type_id'=>2,'opening_balance'=>0]

        ]);
    }
}
